#!/bin/sh
#
# Runs at the end of git flow release start
#
# Positional arguments:
# $1    The version (including the version prefix)
# $2    The origin remote
# $3    The full branch name (including the release prefix)
# $4    The base from which this release is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop
#
VERSION=$1
ORIGIN=$2
BRANCH=$3
BASE=$4

. "$(dirname "$0")/maven-common.sh"

$MAVEN_CMD versions:set -DnewVersion=$VERSION-SNAPSHOT -DgenerateBackupPoms=false
git commit --all --message="build: bump version number to $VERSION-SNAPSHOT"

exit 0
